services:
  - type: web
    name: scrum-poker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k worker.JsonPatchedWorker -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        generateValue: true

